from main import *
try:
	while True: main_task()
except Exception as e:
	print(mistake())
	#print(e)